language: php
php:
  - 5.5
  - 5.4
deploy:
  skip_cleanup: true
script: phpunit Test.php
os:
  - linux
##notifications:
##  email: false
##  slack:
##    secure: ""

language: node_js
node_js:
  - 10.6.0
install:
  - gem install sass
  - gem install compass
script:
  - compass compile