# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
# テスト
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:5.6-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
          - "2d:87:63:05:f2:99:a5:cb:ff:a7:c9:73:a7:43:8d:39"

#      - run:
#          name: Start ssh-keyscan
#          command: |
#            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
#
#      - deploy:
#          name: Start master deploy
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
#                rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/var/www/html/
#            fi
      - run: echo "User ec2-user" >> $HOME/.ssh/config
      - run: echo "ForwardAgent yes" >> $HOME/.ssh/config
      - run: yum -y install php-pear php-devel
      - run: curl -LO https://deployer.org/releases/v4.3.1/deployer.phar
      - run: mv deployer.phar dep
      - run: chmod +x ./dep
      - run: ./dep deploy staging
