# circleCIのバージョン指定
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
           fingerprints:
             - "c2:86:1e:f1:8a:49:16:f9:27:99:0a:0a:bd:57:88:42" 
      - run:
           name: Deploy Over SSH
      - run: echo ${CIRCLE_BRANCH} # run the `echo` command
# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     # masterブランチがpushされた場合のみdeployするようにする。
      #     filters:
      #       branches:
      #         only: master